[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }